### ISSUE TITLE
dbt doc generation

### ISSUE THREAD

**Issue by singhalong21** [Datavault-UK/dbtvault-docs#12]
Hello dbtvault team,
I followed your dbtvault guidelines and could build a decent datavault.
But now I want to add the documentation, which could be added later in dbt generate. But it doesnt seem to work.

As per dbtvault approach, its better that we do not put the metadata reference in dbt_project.yml file. [ref](https://dbtvault.readthedocs.io/en/latest/metadata/#approaches)
So I tried "Per Model - variables" approach. [ref](https://dbtvault.readthedocs.io/en/latest/metadata/#per-model-variables)

But this conflicts with dbt guidelines. [ref](https://docs.getdbt.com/docs/building-a-dbt-project/documentation#adding-descriptions-to-your-project)

dbt says we should add these in yml files and not model files. I even tried "Per Model - YAML strings" approach [ref](https://dbtvault.readthedocs.io/en/latest/metadata/#per-model-yaml-strings). And added description there. But dbt gives error there.

Can somebody help me with tips and/or fix this issue?

**Comment by DVAlexHiggs** [comment]
The metadata reference is for providing metadata to dbtvault macros **only**. For everything else you should follow the standard documentation provided by dbt. These should be provided in YAML files and not docs files as you have said, and the dbt docs provide instructions on how to do so correctly. if you are having issues then please consult the dbt documentation or ask on their slack channel, which is full o very friendly and helpful people. Thanks!
