### ISSUE TITLE
[BUG] Problem in documentation on web site.

### ISSUE THREAD

**Issue by mjahammel** [Datavault-UK/dbtvault-docs#50]
**Describe the bug**
There appears to be a problem in the documentation on the page https://dbtvault.readthedocs.io/en/latest/metadata/, in the section: Extended Tracking Satellites (XTS) -> Per-model - YAML strings -> Tracking multiple satellites.

The code presented on the page is:

![image](https://user-images.githubusercontent.com/3769193/206768204-1d9f643f-37bc-43d9-a638-64a69dbfc30c.png)

*Expected behaviour*

Shouldn't the text in the red box be: `SAT_ORDER_DETAILS`?  Like so:

![image](https://user-images.githubusercontent.com/3769193/206768801-2fe62f33-52f2-4751-b06d-5e26491e8609.png)

**Comment by DVAlexHiggs** [comment]
Thanks! This will be corrected :)

**Comment by DVAlexHiggs** [comment]
Updated!
